name: app1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.17.0
  firebase_auth: ^4.17.6
  firebase_auth_web: ^5.7.6
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/Houses_on_shore.jpg
    - assets/image/landmarks.png
flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/image/landmarks.png
  image_dark: assets/image/landmarks.png
  android: true
  ios: true
  web: false
  fullscreen: true